# Development Environment Overrides
# These settings override the base configuration for development

workspace:
  name: analytics-workspace-dev # Dev-specific naming
  capacity_id: F2 # Smaller capacity for development
  git_branch: develop # Use develop branch

# Minimal setup for development
lakehouses:
  - name: dev_raw_data
    folder: Bronze
    description: Development raw data (subset)

# Development team access
principals:
  - id: sanmi.ibitoye@leit.com
    role: Admin

  - id: 9117cbfa-f0a7-43b7-846f-96ba66a3c1c0
    role: Admin

  # Mandatory Security Principals
  - id: "f21d0f2e-f041-4ccc-8a13-c05abfaa886c" # EU-M365-SEC-EMEA-AZ-PBI-IT-ADMIN
    role: "Admin"
  
  - id: "c1f65310-9bff-4feb-af93-535785d3003d" # EU-M365-SEC-EMEA-AZ-PBI-EDP-SUPPORT
    role: "Contributor"